services:
  db:
    image: postgres:15.9-alpine3.20
    container_name: postgres_db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
#    command: >
#      sh -c "
#      poetry run alembic upgrade head &&
#      poetry run uvicorn main:app --host 0.0.0.0 --port 8000
#      "
volumes:
  postgres_data: